"""Перечень действий аудита из раздела 18 спецификации.

Список закрытый: бекендер не придумывает названия действий на месте,
иначе журнал становится непригодным для фильтрации и отчётности.
"""

from __future__ import annotations

from enum import StrEnum


class AuditAction(StrEnum):
    # --- Пользователи ---
    USER_CREATED = "USER_CREATED"
    USER_INVITED = "USER_INVITED"
    USER_ACTIVATED = "USER_ACTIVATED"
    # Раздел 18 перечисляет минимум; изменение профиля без смены роли тоже
    # обязано быть видно в журнале, иначе правка команды или руководителя
    # остаётся неотслеженной.
    USER_UPDATED = "USER_UPDATED"
    USER_BLOCKED = "USER_BLOCKED"
    USER_UNBLOCKED = "USER_UNBLOCKED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    USER_OFFBOARDED = "USER_OFFBOARDED"
    USER_TERMINATED = "USER_TERMINATED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    PASSWORD_RESET = "PASSWORD_RESET"
    CONSENT_ACCEPTED = "CONSENT_ACCEPTED"
    SESSIONS_TERMINATED = "SESSIONS_TERMINATED"

    TEAM_CREATED = "TEAM_CREATED"
    TEAM_UPDATED = "TEAM_UPDATED"

    # --- Сделки ---
    DEAL_CREATED = "DEAL_CREATED"
    DEAL_UPDATED = "DEAL_UPDATED"
    DEAL_STATUS_CHANGED = "DEAL_STATUS_CHANGED"
    DEAL_OWNER_CHANGED = "DEAL_OWNER_CHANGED"
    DEAL_CLOSED = "DEAL_CLOSED"
    DEAL_REASSIGNED_BULK = "DEAL_REASSIGNED_BULK"

    # Раздел 18 перечисляет минимум и не называет задачи отдельно, но
    # `tasks` — такая же изменяемая сущность со своими ручками (раздел 6.6),
    # и требование «100% изменяющих данные действий — в аудите» (часть 0,
    # критерий 2) распространяется и на неё. Тот же принцип, что уже дал
    # `USER_UPDATED` сверх минимума.
    TASK_CREATED = "TASK_CREATED"
    TASK_UPDATED = "TASK_UPDATED"
    TASK_COMPLETED = "TASK_COMPLETED"

    # --- Комментарии и файлы ---
    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"
    FILE_UPLOAD_INTENT = "FILE_UPLOAD_INTENT"
    FILE_COMMITTED = "FILE_COMMITTED"
    FILE_INFECTED = "FILE_INFECTED"
    FILE_DOWNLOADED = "FILE_DOWNLOADED"
    FILE_DELETED = "FILE_DELETED"
    ATTACHMENT_CREATED = "ATTACHMENT_CREATED"
    ATTACHMENT_DELETED = "ATTACHMENT_DELETED"

    # --- Импорт и отчёты ---
    IMPORT_STARTED = "IMPORT_STARTED"
    IMPORT_APPLIED = "IMPORT_APPLIED"
    IMPORT_ROLLBACK = "IMPORT_ROLLBACK"
    REPORT_EXPORTED = "REPORT_EXPORTED"
    REPORT_FAILED = "REPORT_FAILED"

    # --- Workflow ---
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_PUBLISHED = "WORKFLOW_PUBLISHED"
    WORKFLOW_VALIDATED = "WORKFLOW_VALIDATED"
    STATUS_ARCHIVED = "STATUS_ARCHIVED"
    STATUS_MAPPING_STARTED = "STATUS_MAPPING_STARTED"
    STATUS_MAPPING_COMPLETED = "STATUS_MAPPING_COMPLETED"

    # --- Организации и ЕГРЮЛ ---
    ORGANIZATION_CREATED = "ORGANIZATION_CREATED"
    ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED"
    ORGANIZATION_DUPLICATE_FOUND = "ORGANIZATION_DUPLICATE_FOUND"
    ORG_REGISTRY_IMPORTED = "ORG_REGISTRY_IMPORTED"
    ORG_DRIFT_APPLIED = "ORG_DRIFT_APPLIED"
    ORG_LIQUIDATION_DETECTED = "ORG_LIQUIDATION_DETECTED"

    # --- ПЭП ---
    SIGNATURE_DOCUMENT_CREATED = "SIGNATURE_DOCUMENT_CREATED"
    SIGNATURE_DOCUMENT_SENT = "SIGNATURE_DOCUMENT_SENT"
    SIGNATURE_VIEWED = "SIGNATURE_VIEWED"
    SIGNATURE_CHALLENGED = "SIGNATURE_CHALLENGED"
    SIGNATURE_SIGNED = "SIGNATURE_SIGNED"
    SIGNATURE_REJECTED = "SIGNATURE_REJECTED"
    SIGNATURE_VOID = "SIGNATURE_VOID"
    SIGNATURE_VERIFIED = "SIGNATURE_VERIFIED"
    SIGNATURE_OTP_FAILED = "SIGNATURE_OTP_FAILED"
    SIGNATURE_KEY_COMPROMISED = "SIGNATURE_KEY_COMPROMISED"
    EDM_AGREEMENT_CREATED = "EDM_AGREEMENT_CREATED"
    EDM_AGREEMENT_REVOKED = "EDM_AGREEMENT_REVOKED"

    # --- 152-ФЗ ---
    ERASURE_REQUEST_CREATED = "ERASURE_REQUEST_CREATED"
    ERASURE_REQUEST_BLOCKED = "ERASURE_REQUEST_BLOCKED"
    ERASURE_REQUEST_APPROVED = "ERASURE_REQUEST_APPROVED"
    ERASURE_REQUEST_REJECTED = "ERASURE_REQUEST_REJECTED"
    ERASURE_EXECUTED = "ERASURE_EXECUTED"
    PII_ACCESS = "PII_ACCESS"
    PII_REVEALED = "PII_REVEALED"
    MASS_EXPORT = "MASS_EXPORT"

    # --- Система ---
    LOGIN_SUCCEEDED = "LOGIN_SUCCEEDED"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"
    SESSION_TERMINATED = "SESSION_TERMINATED"
    AUDIT_EXPORTED = "AUDIT_EXPORTED"
    # Принцип «четырёх глаз» (CRM-1902): заявка, подтверждение и отказ.
    ADMIN_APPROVAL_REQUESTED = "ADMIN_APPROVAL_REQUESTED"
    ADMIN_APPROVAL_GRANTED = "ADMIN_APPROVAL_GRANTED"
    ADMIN_APPROVAL_REJECTED = "ADMIN_APPROVAL_REJECTED"
    FEATURE_FLAG_CHANGED = "FEATURE_FLAG_CHANGED"
    SYSTEM_SETTING_CHANGED = "SYSTEM_SETTING_CHANGED"
    ACCESS_DENIED = "ACCESS_DENIED"
